export enum BaiduPlaceType {
  宾馆 = 'hotel',
  交通设施 = 'transitStation',
  教育 = 'organization',
  公司企业 = 'organization',
  美食 = 'organization',
  酒店 = 'hotel',
  购物 = 'organization',
  生活服务 = 'organization',
  旅游景点 = 'attractions',
  丽人 = 'organization',
  休闲娱乐 = 'organization',
  运动健身 = 'organization',
  教育培训 = 'organization',
  文化传媒 = 'organization',
  医疗 = 'organization',
  汽车服务 = 'organization',
  金融 = 'organization',
  房地产 = 'organization',
  政府机构 = 'organization',
  出入口 = 'organization',
  自然地物 = 'organization',
}
